#!/bin/sh
#
# backup: Overrides the `container-backup()` function from the upstream container
#         this file should be coppied to /etc/container/backup` via the 'Containerfile`.

container_backup() {
}
