kind: pipeline
type: kubernetes
name: Continuous Integration

steps:
- name: build-arm
  image: docker.io/gautada/builder:3.2.3-r1-arm
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: username.docker.io
    DOCKER_PASSWORD:
      from_secret: password.docker.io
    PODMAN_KEY_ARM:
      from_secret: podman.key.arm
    PODMAN_CERT_ARM:
      from_secret: podman.cert.arm
    PODMAN_KEY_x86:
      from_secret: podman.key.x86
    PODMAN_CERT_x86:
      from_secret: podman.cert.x86
    ALPINE_TAG: 3.14.2
    OCI_VERSION: 3.2.3-r1
    OCI_CONTAINER: podman
    OCI_REPOSITORY: docker://docker.io/gautada
    OCI_CPU: aarch64
  commands:
  - /builder-base 5
  - podman --remote --connection arm build --build-arg ALPINE_TAG=3.14.2 --build-arg VERSION=3.2.3-r1 --file Containerfile --no-cache  --tag podman:dev .
  - podman --remote --connection arm tag podman:dev docker.io/gautada/podman:3.2.3-r1-arm
  - podman --remote --connection arm login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
  - podman --remote --connection arm push docker.io/gautada/podman:3.2.3-r1-arm

trigger:
  branch:
  - dev


