#!/bin/sh
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)


container_version() {
 /usr/bin/podman --version |  awk -F ' ' '{print $3}'
}

container_entrypoint() {
 PODMAN_PORT=2375
 /usr/bin/podman system connection add --default default tcp://localhost:$PODMAN_PORT
 /usr/bin/podman system connection add service tcp://podman.code.svc.cluster.local:$PODMAN_PORT
 /usr/bin/sudo /usr/bin/podman --log-level debug system service --time 0 tcp://0.0.0.0:$PODMAN_PORT 
}
