#!/bin/sh

# Luanch the ssh bastion and podman API Service, keep alive for 24hours.

# DEFAULT_SLEEP=86400
# if [ ! -z $1 ] ; then
#  DEFAULT_SLEEP=$1
# fi
#
# if [ ! -f /etc/ssh/ssh_host_rsa_key ] ; then
#  sudo cp /etc/builder/id_rsa /etc/ssh/ssh_host_rsa_key
#  sudo chmod 600 /etc/ssh/ssh_host_rsa_key
# fi
#
# if [ ! -f /etc/ssh/ssh_host_rsa_key.pub ] ; then
#  sudo cp /etc/builder/id_rsa.pub /etc/ssh/ssh_host_rsa_key.pub
#  sudo chmod 600 /etc/ssh/ssh_host_rsa_key.pub
# fi
#
# if [ ! -d /home/bob/.ssh ] ; then
#  mkdir ~/.ssh
# fi
#
# if [ ! -f /home/bob/.ssh/id_rsa ] ; then
#  cp /etc/builder/id_rsa /home/bob/.ssh/id_rsa
#  chmod 600 /home/bob/.ssh/id_rsa
# fi
#
# if [ ! -f /home/bob/.ssh/id_rsa.pub ] ; then
#  cp /etc/builder/id_rsa.pub /home/bob/.ssh/id_rsa.pub
#  chmod 600 /home/bob/.ssh/id_rsa.pub
# fi
#
# if [ ! -f /home/bob/.ssh/authorized_keys ] ; then
#  cat /home/bob/.ssh/id_rsa.pub > /home/bob/.ssh/authorized_keys
#  chmod 600 /home/bob/.ssh/authorized_keys
# fi

# ---------- [ SSH ] ----------
# Check is host keys (try just RSA key) are available otherwise generate keys
if [ ! -f /etc/ssh/ssh_host_rsa_key ] ; then
 /usr/bin/sudo /usr/bin/ssh-keygen -A
fi
# Check that server side keys are generated
if [ ! -f /home/bob/.ssh/podman_key ] ; then
  /usr/bin/ssh-keygen -f /home/bob/.ssh/podman_key -N ''
  cp /home/bob/.ssh/podman_key.pub /home/bob/.ssh/authorized_keys
fi
/usr/bin/sudo /usr/sbin/sshd -e -f /etc/ssh/sshd_config

# Launch crond to prune the tree
# ---------- [ CROND ] ----------
/usr/bin/sudo /usr/sbin/crond -b

# ---------- [ PODMAN ] ----------
if [ -z $LOG_LEVEL ] ; then
 LOG_LEVEL=info
fi
echo "Podman log level:$LOG_LEVEL"
/usr/bin/podman --log-level $LOG_LEVEL system service --time 0
